### ISSUE TITLE
[BUG] <title> is not a legal path

### ISSUE THREAD

**Issue by AlgoLaser-Developer** [dromara/hertzbeat#1034]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
2023-06-21 14:11:36,049 [pool-16-IoTDB-RPC-Client-3] WARN  o.a.i.d.u.ErrorHandlingUtils:168 - Status code: PATH_ILLEGAL(315), operation: insertTablet failed 
2023-06-21T06:11:36.050186928Z org.apache.iotdb.db.exception.metadata.IllegalPathException: root.hertzbeat.ssl_cert.certificate.265623748344832."CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US" is not a legal path
2023-06-21T06:11:36.050189802Z 	at org.apache.iotdb.db.metadata.utils.MetaUtils.splitPathToDetachedPath(MetaUtils.java:80)
2023-06-21T06:11:36.050191469Z 	at org.apache.iotdb.db.metadata.path.PartialPath.<init>(PartialPath.java:81)
2023-06-21T06:11:36.050192903Z 	at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.insertTablet(TSServiceImpl.java:1614)
2023-06-21T06:11:36.050194133Z 	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertTablet.getResult(TSIService.java:3601)
2023-06-21T06:11:36.050199948Z 	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertTablet.getResult(TSIService.java:3581)
2023-06-21T06:11:36.050201177Z 	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
2023-06-21T06:11:36.050202287Z 	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
2023-06-21T06:11:36.050203404Z 	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
```

### Steps To Reproduce

https://github.com/dromara/hertzbeat/tree/master/script/docker-compose/hertzbeat-mysql-iotdb

### Environment

```markdown
HertzBeat version(s):v1.3.1
```

**Comment by AlgoLaser-Developer** [comment]
https://github.com/dromara/hertzbeat/issues/1035

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
https://github.com/dromara/hertzbeat/issues/1035

**Comment by tomsun28** [comment]
same issue, close this one
