### ISSUE TITLE
[BUG] <title>is not a legal path

### ISSUE THREAD

**Issue by AlgoLaser-Developer** [dromara/hertzbeat#1035]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
2023-06-21 14:11:36,049 [pool-16-IoTDB-RPC-Client-3] WARN  o.a.i.d.u.ErrorHandlingUtils:168 - Status code: PATH_ILLEGAL(315), operation: insertTablet failed 
2023-06-21T06:11:36.050186928Z org.apache.iotdb.db.exception.metadata.IllegalPathException: root.hertzbeat.ssl_cert.certificate.265623748344832."CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US" is not a legal path
2023-06-21T06:11:36.050189802Z 	at org.apache.iotdb.db.metadata.utils.MetaUtils.splitPathToDetachedPath(MetaUtils.java:80)
2023-06-21T06:11:36.050191469Z 	at org.apache.iotdb.db.metadata.path.PartialPath.<init>(PartialPath.java:81)
2023-06-21T06:11:36.050192903Z 	at org.apache.iotdb.db.service.thrift.impl.TSServiceImpl.insertTablet(TSServiceImpl.java:1614)
2023-06-21T06:11:36.050194133Z 	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertTablet.getResult(TSIService.java:3601)
2023-06-21T06:11:36.050199948Z 	at org.apache.iotdb.service.rpc.thrift.TSIService$Processor$insertTablet.getResult(TSIService.java:3581)
2023-06-21T06:11:36.050201177Z 	at org.apache.thrift.ProcessFunction.process(ProcessFunction.java:38)
2023-06-21T06:11:36.050202287Z 	at org.apache.thrift.TBaseProcessor.process(TBaseProcessor.java:38)
2023-06-21T06:11:36.050203404Z 	at org.apache.thrift.server.TThreadPoolServer$WorkerProcess.run(TThreadPoolServer.java:248)
```

### Steps To Reproduce

https://github.com/dromara/hertzbeat/tree/master/script/docker-compose/hertzbeat-mysql-iotdb

### Environment

```markdown
HertzBeat version(s):v1.3.1
```

**Comment by AlgoLaser-Developer** [comment]
[v1.2.5] is the same error

**Comment by tomsun28** [comment]
> [v1.2.5] is the same error

got it 🫡 thanks.

**Comment by guojing1983** [comment]
Docker version 24.0.2, build cb74dfc 参考 https://github.com/dromara/hertzbeat/tree/master/script/docker-compose/hertzbeat-mysql-iotdb 部署，正常运行
![image](https://github.com/dromara/hertzbeat/assets/60596094/b52dfc19-b189-40b8-b92e-efcff90ba0e5)
![image](https://github.com/dromara/hertzbeat/assets/60596094/8e8a1727-46d4-4efb-8423-f6611d37b1d3)

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Docker version 24.0.2, build cb74dfc refer to https://github.com/dromara/hertzbeat/tree/master/script/docker-compose/hertzbeat-mysql-iotdb deployment, running normally
![image](https://github.com/dromara/hertzbeat/assets/60596094/b52dfc19-b189-40b8-b92e-efcff90ba0e5)
![image](https://github.com/dromara/hertzbeat/assets/60596094/8e8a1727-46d4-4efb-8423-f6611d37b1d3)

**Comment by geekyouth** [comment]
你的截图完全没有任何说服力，问题的根源在于，mysql 入库过程中，字段值存在特殊符号，需要做转义或者特殊编码，否则，会导致值写入出错。具体的字段值，是 SSL 证书信息的描述，存在换行符和双引号，这些特殊符号必须要转义。
---
Your screenshot is completely unconvincing. The root cause of the problem lies in the fact that during the process of storing data into MySQL, there are special characters present in the field values that need to be escaped or encoded properly; otherwise, it will result in writing errors. Specifically, these field values describe SSL certificate information and contain newline characters and double quotation marks. These special symbols must be escaped.
