### ISSUE TITLE
升级1.4启动报错

### ISSUE THREAD

**Issue by xiaoka712** [dromara/hertzbeat#1204]
### Question

ERROR org.dromara.hertzbeat.warehouse.store.HistoryIotDbDataStorage - 313: failed to insert measurements [read_only] caused by DataT
ype mismatch, Insert measurement read_only type TEXT, metadata tree type DOUBLE
org.apache.iotdb.rpc.StatementExecutionException: 313: failed to insert measurements [read_only] caused by DataType mismatch, Insert measurement read_only type TEXT, metadata tree type DOU
BLE
        at org.apache.iotdb.rpc.RpcUtils.verifySuccess(RpcUtils.java:98)
        at org.apache.iotdb.rpc.RpcUtils.verifySuccessWithRedirection(RpcUtils.java:119)
        at org.apache.iotdb.session.SessionConnection.verifySuccessWithRedirectionWrapper(SessionConnection.java:526)
        at org.apache.iotdb.session.SessionConnection.insertTablet(SessionConnection.java:643)
        at org.apache.iotdb.session.Session.insertTablet(Session.java:2139)
        at org.apache.iotdb.session.pool.SessionPool.insertTablet(SessionPool.java:576)
        at org.dromara.hertzbeat.warehouse.store.HistoryIotDbDataStorage.saveData(HistoryIotDbDataStorage.java:237)
        at org.dromara.hertzbeat.warehouse.store.DataStorageDispatch.lambda$startStoragePersistentData$3(DataStorageDispatch.java:91)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by tomsun28** [comment]
hi what the iotdb version used?

**Comment by xiaoka712** [comment]
您好！
------------------------------------------------------------------
发件人：tomsun28 ***@***.***>
发送时间：2023年8月24日(星期四) 22:12
收件人：dromara/hertzbeat ***@***.***>
抄　送：杨翾 ***@***.***>; Author ***@***.***>
主　题：Re: [dromara/hertzbeat] upgrade 1.4 startup error (Issue #1204)
hi what the iotdb version used?

**Comment by xiaoka712** [comment]
您好！我得iotdb版本为0.13.4

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hello! I have iotdb version 0.13.4
