### ISSUE TITLE
1.4 version running error

### ISSUE THREAD

**Issue by rmsto** [dromara/hertzbeat#1253]
### Question

1.4版本运行报错，报错日志截取如下：
**### 报错一**
2023-09-15 18:00:31.390 [296107104818944-ping-summary-5383] INFO  org.dromara.hertzbeat.collector.dispatch.MetricsCollect Line:386 - [Collect Failed, Run 6007ms, All 6008ms] Reason: Un Reachable, Timeout 6000ms
2023-09-15 18:00:31.590 [alerter-worker-0] ERROR org.dromara.hertzbeat.common.util.JsonUtil Line:54  - Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: org.dromara.hertzbeat.common.entity.alerter.Alert["gmtCreate"])
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: org.dromara.hertzbeat.common.entity.alerter.Alert["gmtCreate"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
	at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
	at org.dromara.hertzbeat.common.util.JsonUtil.toJson(JsonUtil.java:52)
	at org.dromara.hertzbeat.manager.component.alerter.impl.WeChatAppAlertNotifyHandlerImpl.send(WeChatAppAlertNotifyHandlerImpl.java:63)
	at org.dromara.hertzbeat.manager.component.alerter.DispatcherAlarm.sendNoticeMsg(DispatcherAlarm.java:89)
	at org.dromara.hertzbeat.manager.component.alerter.DispatcherAlarm$DispatchTask.sendNotify(DispatcherAlarm.java:127)
	at org.dromara.hertzbeat.manager.component.alerter.DispatcherAlarm$DispatchTask.run(DispatcherAlarm.java:110)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

**### 报错二**
配置了企业微信应用报警，确认配置没有问题，但是实际监控发下问题后平台已收到消息，但是企业微信无法收到报警
2023-09-15 18:00:31.789 [alerter-worker-0] WARN  org.dromara.hertzbeat.manager.component.alerter.impl.WeChatAppAlertNotifyHandlerImpl Line:75  - Send Enterprise WeChat App Error: empty content, hint: [1694772031640291637430873], from ip: 61.198.100.241, more info at https://open.work.weixin.qq.com/devtool/query?e=44004
2023-09-15 18:00:31.789 [alerter-worker-0] WARN  org.dromara.hertzbeat.manager.component.alerter.DispatcherAlarm Line:129 - DispatchTask sendNoticeMsg error, message: [Enterprise WeChat Notify Error] Http StatusCode 200 OK Error: empty content, hint: [1694772031640291637430873], from ip: 61.198.100.241, more info at https://open.work.weixin.qq.com/devtool/query?e=44004
2023-09-15 18:00:44.685 [scheduling-1] WARN  org.dromara.hertzbeat.warehouse.store.HistoryJpaDatabaseDataStorage Line:69  - [jpa-metrics-store]-start running expired data cleaner.Please use time series db instead of jpa for better performance
2023-09-15 18:00:44.686 [scheduling-1] INFO  org.dromara.hertzbeat.warehouse.store.HistoryJpaDatabaseDataStorage Line:89  - [jpa-metrics-store]-delete 0 rows.

**Comment by gcdd1993** [comment]
@rmsto 你好，企业微信应用要配置IP白名单，详情查看：https://open.work.weixin.qq.com/devtool/query?e=44004

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
@rmsto Hello, the enterprise WeChat application needs to configure an IP whitelist. For details, check: https://open.work.weixin.qq.com/devtool/query?e=44004
