### ISSUE TITLE
Any type of monitoring history chart details chart data is empty. Background log report [ILLEGAL_PATH(509)]

### ISSUE THREAD

**Issue by langcui** [dromara/hertzbeat#1307]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

2023-11-01 10:57:40 [warehouse-persistent-data-storage] ERROR org.dromara.hertzbeat.warehouse.store.HistoryIotDbDataStorage - 509: [ILLEGAL_PATH(509)] Exception occurred: insertTablet failed. root.hertzbeat.kubernetes.namespaces.312400665675776 is not a legal path
org.apache.iotdb.rpc.StatementExecutionException: 509: [ILLEGAL_PATH(509)] Exception occurred: insertTablet failed. root.hertzbeat.kubernetes.namespaces.312400665675776 is not a legal path
at org.apache.iotdb.rpc.RpcUtils.verifySuccess(RpcUtils.java:98)
at org.apache.iotdb.rpc.RpcUtils.verifySuccessWithRedirection(RpcUtils.java:119)
at org.apache.iotdb.session.SessionConnection.verifySuccessWithRedirectionWrapper(SessionConnection.java:526)
at org.apache.iotdb.session.SessionConnection.insertTablet(SessionConnection.java:643)
at org.apache.iotdb.session.Session.insertTablet(Session.java:2139)
at org.apache.iotdb.session.pool.SessionPool.insertTablet(SessionPool.java:576)
at org.dromara.hertzbeat.warehouse.store.HistoryIotDbDataStorage.saveData(HistoryIotDbDataStorage.java:237)
at org.dromara.hertzbeat.warehouse.store.DataStorageDispatch.lambdastartStoragePersistentData
3(DataStorageDispatch.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

### Expected Behavior

fix it 

### Environment

```markdown
HertzBeat version(s):1.4.1
```

### Debug logs

2023-11-01 10:51:50 [warehouse-persistent-data-storage] ERROR org.dromara.hertzbeat.warehouse.store.HistoryIotDbDataStorage - 509: [ILLEGAL_PATH(509)] Exception occurred: insertTablet failed. root.hertzbeat.elasticsearch.health.312357325518848."elasticsearch" is not a legal path
org.apache.iotdb.rpc.StatementExecutionException: 509: [ILLEGAL_PATH(509)] Exception occurred: insertTablet failed. root.hertzbeat.elasticsearch.health.312357325518848."elasticsearch" is not a legal path
at org.apache.iotdb.rpc.RpcUtils.verifySuccess(RpcUtils.java:98)
at org.apache.iotdb.rpc.RpcUtils.verifySuccessWithRedirection(RpcUtils.java:119)
at org.apache.iotdb.session.SessionConnection.verifySuccessWithRedirectionWrapper(SessionConnection.java:526)
at org.apache.iotdb.session.SessionConnection.insertTablet(SessionConnection.java:643)
at org.apache.iotdb.session.Session.insertTablet(Session.java:2139)
at org.apache.iotdb.session.pool.SessionPool.insertTablet(SessionPool.java:576)
at org.dromara.hertzbeat.warehouse.store.HistoryIotDbDataStorage.saveData(HistoryIotDbDataStorage.java:237)
at org.dromara.hertzbeat.warehouse.store.DataStorageDispatch.lambdastartStoragePersistentData
3(DataStorageDispatch.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Ceilzcx** [comment]
please provide the IoTDB version

**Comment by langcui** [comment]
> please provide the IoTDB version

show version
+-------+---------+
|Version|BuildInfo|
+-------+---------+
|  1.2.2|  5d0bfb0|
+-------+---------+
Total line number = 1
It costs 0.122s

no db created:
show databases
+--------+---+-----------------------+---------------------+---------------------+
|Database|TTL|SchemaReplicationFactor|DataReplicationFactor|TimePartitionInterval|
+--------+---+-----------------------+---------------------+---------------------+
+--------+---+-----------------------+---------------------+---------------------+
Empty set.

**Comment by langcui** [comment]
hertzbeat version 1.4.1, tks

**Comment by Ceilzcx** [comment]
@langcui do you change this config in application.yml? the path since V_0_13
![image](https://github.com/dromara/hertzbeat/assets/48920254/2110475f-1ba0-4d81-bd5f-5349a9531f23)

**Comment by langcui** [comment]
> @langcui do you change this config in application.yml? the path since V_0_13 ![image](https://user-images.githubusercontent.com/48920254/280173218-2110475f-1ba0-4d81-bd5f-5349a9531f23.png)

Tks, change to iotdb:v0.13, resolved.
