### ISSUE TITLE
[BUG] <access vm http api error when store metrics data>

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#1541]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sometime Unexpected end of file from server
sometime Connection refused (Connection refused)
sometime read timeout

### Environment

```markdown
HertzBeat version(s): 1.4.4
```

### Debug logs

2024-02-07 23:06:30 [warehouse-persistent-data-storage] ERROR org.dromara.hertzbeat.warehouse.store.HistoryVictoriaMetricsDataStorage - flush metrics data to victoria-metrics error: I/O error on POST request for "http://82.157.76.80:8428/api/v1/import": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server.
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "http://82.157.76.80:8428/api/v1/import": Unexpected end of file from server; nested exception is java.net.SocketException: Unexpected end of file from server
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:468)
	at org.dromara.hertzbeat.warehouse.store.HistoryVictoriaMetricsDataStorage.saveData(HistoryVictoriaMetricsDataStorage.java:181)
	at org.dromara.hertzbeat.warehouse.store.DataStorageDispatch.lambda$startStoragePersistentData$3(DataStorageDispatch.java:88)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.net.SocketException: Unexpected end of file from server
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:866)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1615)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:55)
	at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:61)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:807)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:777)
	... 7 common frames omitted

**Comment by zqr10159** [comment]
[https://github.com/dromara/hertzbeat/commit/f866a260e024124e3fa5c6708233510b656ced51](url)
