### ISSUE TITLE
website monitor - [Metrics Collect]: Illegal character in path at index 

### ISSUE THREAD

**Issue by tomsun28** [dromara/hertzbeat#3]
采集器对某个website网站监控进行采集时异常，初步判断URL不规范导致
异常堆栈：
2022-03-03 23:13:56.524 [6134408644919296-website-summary-6524] ERROR com.usthe.collector.dispatch.MetricsCollect Line:132 - [Metrics Collect]: Illegal character in path at index 35: https://xxxxxxxxx.com:80/ccccccday/ .
java.lang.IllegalArgumentException: Illegal character in path at index 35: https://xxxxxxxxx.com:80/ccccccday/ 
	at java.net.URI.create(URI.java:852)
	at org.apache.http.client.methods.RequestBuilder.setUri(RequestBuilder.java:345)
	at com.usthe.collector.collect.http.HttpCollectImpl.createHttpRequest(HttpCollectImpl.java:457)
	at com.usthe.collector.collect.http.HttpCollectImpl.collect(HttpCollectImpl.java:81)
	at com.usthe.collector.dispatch.MetricsCollect.run(MetricsCollect.java:126)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in path at index 35: https://xxxxxxxxx.com:80/ccccccday/ 
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 7 common frames omitted

**Comment by tomsun28** [comment]
fix by pr #5
