### ISSUE TITLE
[BUG] <Ubuntu Linux monitoring exception java.lang.ArrayIndexOutOfBoundsException>

### ISSUE THREAD

**Issue by AbnerSC** [dromara/hertzbeat#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

异常内容：
java.lang.ArrayIndexOutOfBoundsException: Index 5 out of bounds for length 5
	at com.usthe.collector.collect.ssh.SshCollectImpl.parseResponseDataByOne(SshCollectImpl.java:180)
	at com.usthe.collector.collect.ssh.SshCollectImpl.collect(SshCollectImpl.java:106)
	at com.usthe.collector.dispatch.MetricsCollect.run(MetricsCollect.java:146)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

### Expected Behavior

1. 后台运行报错

### Steps To Reproduce

1. 定时扫描Ubuntu Linux时后台抛出异常

### Environment

```markdown
HertzBeat version(s): 1.3.0
```

### Debug logs

[83781b0375ac10-2023-03-16.0.log](https://github.com/dromara/hertzbeat/files/10986374/83781b0375ac10-2023-03-16.0.log)

### Anything else?

关联BUG：#732

**Comment by tomsun28** [comment]
append: 
2023-03-13 19:03:08.603 [230296542992384-ubuntu-basic-8572] INFO  com.usthe.collector.collect.ssh.SshCollectImpl Line:122 - open failed
2023-03-13 19:03:08.627 [230296542992384-ubuntu-basic-8572] INFO  com.usthe.collector.dispatch.MetricsCollect Line:388 - [Collect Failed, Run 55ms, All 56ms] Reason: Peer connection failed: open failed

**Comment by tomsun28** [comment]
fix by v1.3.1
