### ISSUE TITLE
SQL server driver connection error [BUG] <title>

### ISSUE THREAD

**Issue by sunxq86** [dromara/hertzbeat#927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The default driver is jdk 8,
I replaced the JDK 11 and  error during startup
ERROR：
[root@localhost logs]# cat localhost.localdomain70635-2023-05-04-error.0.log
2023-05-04 16:03:08.246 [main] ERROR com.usthe.collector.collect.database.JdbcSpiLoader Line:47  - load jdbc error: com.microsoft.sqlserver.jdbc.SQLServerDriver
java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.usthe.collector.collect.database.JdbcSpiLoader.run(JdbcSpiLoader.java:42)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at com.usthe.manager.Manager.main(Manager.java:40)
2023-05-04 16:03:09.444 [scheduling-1] ERROR com.usthe.warehouse.store.HistoryJpaDatabaseDataStorage Line:71  - expiredDataCleaner database error: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call; nested exception is javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call.

### Expected Behavior

./startup.sh

### Steps To Reproduce

1,download [Microsoft JDBC Driver 12.2 for SQL Server (tar.gz)]
https://learn.microsoft.com/zh-cn/sql/connect/jdbc/download-microsoft-jdbc-driver-for-sql-server?view=sql-server-ver16

2,change driver
cd /opt/hertzbeat/lib
rm mssql-jdbc-10.2.1.jre8.jar
mv mssql-jdbc-12.2.0.jre11.jar /opt/hertzbeat/lib
chmod 775 mssql-jdbc-12.2.0.jre11.jar

3,startup
cd /opt/hertzbeat/bin
./startup.sh

### Environment

```markdown
HertzBeat version(s):1.3.0
```

### Debug logs

[root@localhost logs]# cat localhost.localdomain70635-2023-05-04-error.0.log
2023-05-04 16:03:08.246 [main] ERROR com.usthe.collector.collect.database.JdbcSpiLoader Line:47  - load jdbc error: com.microsoft.sqlserver.jdbc.SQLServerDriver
java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at com.usthe.collector.collect.database.JdbcSpiLoader.run(JdbcSpiLoader.java:42)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:771)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:755)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
        at com.usthe.manager.Manager.main(Manager.java:40)
2023-05-04 16:03:09.444 [scheduling-1] ERROR com.usthe.warehouse.store.HistoryJpaDatabaseDataStorage Line:71  - expiredDataCleaner database error: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call; nested exception is javax.persistence.TransactionRequiredException: No EntityManager with actual transaction available for current thread - cannot reliably process 'remove' call.

**Comment by zqr10159** [comment]
你好，这不是一个bug，在修改jar文件时，由于之前打包的文件是mssql-jdbc-10.2.1.jre8.jar而不是mssql-jdbc-12.2.0.jre11.jar，所以找不到这个依赖，你需要修改hertzbeat/hertzbeat.jar文件，使用解压缩软件直接修改其中的META-INF/MANIFEST.MF文件，搜索mssql-jdbc-10.2.1.jre8.jar替换为mssql-jdbc-12.2.0.jre11.jar之后运行，就可以了。我测试了可以正常运行。

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
Hello, this is not a bug, when modifying the jar file, since the previously packaged file is mssql-jdbc-10.2.1.jre8.jar instead of mssql-jdbc-12.2.0.jre11.jar, it cannot find this Depends, you need to modify the hertzbeat/hertzbeat.jar file, use the decompression software to directly modify the META-INF/MANIFEST.MF file, search for mssql-jdbc-10.2.1.jre8.jar and replace it with mssql-jdbc-12.2.0 After running .jre11.jar, it will work. I tested it works fine.

**Comment by sunxq86** [comment]
TKS
