### ISSUE TITLE
[Question] <redis>添加redis单机版监控，下标越界 。docker安装版本：v1.3.1

### ISSUE THREAD

**Issue by dmcxiaobing** [dromara/hertzbeat#941]
### Question

2023-05-09 15:05:59 [1000000000-redis-server-9556] WARN  org.dromara.hertzbeat.collector.collect.redis.RedisCommonCollectImpl - [redis collect] error: Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at org.dromara.hertzbeat.collector.collect.redis.RedisCommonCollectImpl.lambda$parseInfo$7(RedisCommonCollectImpl.java:298)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at org.dromara.hertzbeat.collector.collect.redis.RedisCommonCollectImpl.parseInfo(RedisCommonCollectImpl.java:297)
	at org.dromara.hertzbeat.collector.collect.redis.RedisCommonCollectImpl.getSingleRedisInfo(RedisCommonCollectImpl.java:95)
	at org.dromara.hertzbeat.collector.collect.redis.RedisCommonCollectImpl.collect(RedisCommonCollectImpl.java:71)
	at org.dromara.hertzbeat.collector.dispatch.MetricsCollect.run(MetricsCollect.java:145)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-05-09 15:05:59 [1000000000-redis-server-9556] INFO  org.dromara.hertzbeat.collector.dispatch.MetricsCollect - [Collect Failed, Run 1ms, All 1ms] Reason: Index 1 out of bounds for length 1

请问现在redis单机链接有什么特殊配置吗？没找到相关说明资料

**Comment by tomsun28** [comment]
hi this is a bug will be fixed by pr https://github.com/dromara/hertzbeat/pull/942
We will fix it and flush docker image as soon as possible.
